"""vitals clip window, required workout start time, lookup indexes

Revision ID: 65d11828f498
Revises: ac007e8c8c59
Create Date: 2026-09-26 11:52:41.674368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65d11828f498'
down_revision = 'ac007e8c8c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_sets_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('rep_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rep_events_session_id'))
        batch_op.create_index('ix_rep_events_session_time', ['session_id', 'recorded_at'], unique=False)

    with op.batch_alter_table('vitals_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('window_sec', sa.Float(), nullable=True))
        batch_op.create_index('ix_vitals_readings_session_time', ['session_id', 'recorded_at'], unique=False)

    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.create_index('ix_workout_sessions_user_started', ['user_id', 'started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_workout_sessions_user_started')
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('vitals_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_vitals_readings_session_time')
        batch_op.drop_column('window_sec')

    with op.batch_alter_table('rep_events', schema=None) as batch_op:
        batch_op.drop_index('ix_rep_events_session_time')
        batch_op.create_index(batch_op.f('ix_rep_events_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('exercise_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_sets_session_id'))

    # ### end Alembic commands ###
