"""initial schema: users, sessions, sets, vitals, rep events

Revision ID: ac007e8c8c59
Revises: 
Create Date: 2026-09-26 11:30:11.907589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac007e8c8c59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth0_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_auth0_sub'), ['auth0_sub'], unique=True)

    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('total_reps', sa.Integer(), nullable=True),
    sa.Column('avg_heart_rate_bpm', sa.Float(), nullable=True),
    sa.Column('max_heart_rate_bpm', sa.Float(), nullable=True),
    sa.Column('zone_minutes', sa.JSON(), nullable=True),
    sa.Column('form_score', sa.Float(), nullable=True),
    sa.Column('effort_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=120), nullable=False),
    sa.Column('muscle_groups', sa.JSON(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('form_score', sa.Float(), nullable=True),
    sa.Column('range_of_motion', sa.Float(), nullable=True),
    sa.Column('symmetry', sa.Float(), nullable=True),
    sa.Column('avg_rep_seconds', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vitals_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heart_rate_bpm', sa.Float(), nullable=True),
    sa.Column('breathing_rate_bpm', sa.Float(), nullable=True),
    sa.Column('hrv_ms', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id', 'recorded_at')
    )
    op.create_table('rep_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('exercise_name', sa.String(length=120), nullable=False),
    sa.Column('rep_number', sa.Integer(), nullable=False),
    sa.Column('range_of_motion', sa.Float(), nullable=True),
    sa.Column('symmetry', sa.Float(), nullable=True),
    sa.Column('tempo_score', sa.Float(), nullable=True),
    sa.Column('rep_seconds', sa.Float(), nullable=True),
    sa.Column('form_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['exercise_sets.id'], ),
    sa.PrimaryKeyConstraint('id', 'recorded_at')
    )
    with op.batch_alter_table('rep_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rep_events_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rep_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rep_events_session_id'))

    op.drop_table('rep_events')
    op.drop_table('vitals_readings')
    op.drop_table('exercise_sets')
    op.drop_table('workout_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_auth0_sub'))

    op.drop_table('users')
    # ### end Alembic commands ###
